### ISSUE TITLE
Unable to access Preferences

### ISSUE THREAD

**Issue by Rejam** [batterseapower/pinyin-toolkit#108]
I had been using the plug-in for a few days and then began getting the following error message when trying to access the plug-in preferences:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "/Users/ryanjames/Library/Application Support/Anki/plugins/pinyin/anki/hooks.py", line 123, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "/Users/ryanjames/Library/Application Support/Anki/plugins/pinyin/anki/hooks.py", line 146, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "/Users/ryanjames/Library/Application Support/Anki/plugins/pinyin/forms/preferencescontroller.py", line 46, in **init**
    self.updateView()
  File "/Users/ryanjames/Library/Application Support/Anki/plugins/pinyin/forms/preferencescontroller.py", line 188, in updateView
    mapping.updateView()
  File "/Users/ryanjames/Library/Application Support/Anki/plugins/pinyin/forms/preferencescontroller.py", line 263, in updateView
    self.updateViewValue(eval("model." + self.key, { "model" : self.model }))
  File "/Users/ryanjames/Library/Application Support/Anki/plugins/pinyin/forms/preferencescontroller.py", line 313, in updateViewValue
    if utils.fromQVariant(self.combobox.itemData(n)) == value:
  File "/Users/ryanjames/Library/Application Support/Anki/plugins/pinyin/forms/utils.py", line 60, in fromQVariant
    raise ValueError, "Could not convert value to %s" % typeName
ValueError: Could not convert value to None

I have tried removing and re-installing but the error still appears.
The plug-in is still functioning I am just unable to access the preferences panel to make any changes.

**Comment by batterseapower** [comment]
Rejam, thanks for the report. We have already fixed this in the most recent version. The only way to fix this without the latest version installed is to open up your Anki config file and change the "dictlanguage" value to "en" (without the quotes) from whatever it is now. This can be a bit tricky because the config file is in "pickled" format, so let us know if you have problems. Make sure to backup your config before you make the change in case you get it wrong!
