### ISSUE TITLE
anki 0.9.9.8.6 - error when select settings/Pinyin Toolkit preferences

### ISSUE THREAD

**Issue by brendonl** [batterseapower/pinyin-toolkit#155]
1. Using anki 0.9.9.8.6
2. today installed plugin - 13/2/10
3. clicked on settings/Pinyin Toolkit preferences - error below
4. using xp sp3
   Any help appreciated

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\anki\hooks.py", line 156, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\anki\hooks.py", line 137, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 53, in **init**
    self.updateViewPreview()
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 228, in updateViewPreview
    self.updaterfromexpr.updatefact(fact, previewexpressions[self.model.prefersimptrad])
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\updater.py", line 284, in updatefact
    dictreading = self.getdictreading(expression)
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\updater.py", line 249, in getdictreading
    dictreading = lookup()
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\updater.py", line 242, in 
    lambda: numbers.readingfromnumberlike(expression, self.dictionary),
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\updater.py", line 128, in 
    dictionary = property(lambda self: self.dictionaries(self.config.dictlanguage))
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\dictionary.py", line 132, in inner
    return (dictionaries.get(language, None) or dictionaries['default'])()
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\utils.py", line 185, in **call**
    self.__result = self.__function()
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\dictionary.py", line 129, in 
    dictionaries[language] = Thunk(lambda l=language, t=table, sti=simptradindex: buildDictionary(l != 'en', t, sti))
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\dictionary.py", line 118, in buildDictionary
    table and databaseDictionarySource(table, simptradindex) or None,
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin\dictionary.py", line 65, in databaseDictionarySource
    maxcharacterlen = database.selectScalar(sqlalchemy.func.max(sqlalchemy.func.length(dicttable.c.HeadwordSimplified)))
  File "C:\Documents and Settings\Administrator.HOME01\Application Data.anki\plugins\pinyin..\pinyin\vendor\cjklib\cjklib\dbconnector.py", line 207, in selectScalar
    result = self.connection.execute(request)
  File "sqlalchemy\engine\base.pyc", line 824, in execute
  File "sqlalchemy\engine\base.pyc", line 858, in _execute_function
  File "sqlalchemy\engine\base.pyc", line 874, in _execute_clauseelement
  File "sqlalchemy\engine\base.pyc", line 896, in __execute_context
  File "sqlalchemy\engine\base.pyc", line 950, in _cursor_execute
  File "sqlalchemy\engine\base.pyc", line 931, in _handle_dbapi_exception
sqlalchemy.exc.DatabaseError: (DatabaseError) database disk image is malformed u'SELECT max(length("CEDICT"."HeadwordSimplified")) AS max_1 \nFROM "CEDICT"' []

**Comment by batterseapower** [comment]
Does this go away if you delete pinyin/db/cjklib.db, and hence cause the Toolkit to regenerate the database?

**Comment by yinzi** [comment]
still gets this message, plugin also doesn't work at all - all fields blank.

**Comment by spaldos** [comment]
same problem for me. Nothing works at all, no idea why this started happening. Tried reinstalling completely. Worked for months, then yesterday, this. Won't generate fields, and when trying to select the toolkit preferences it throws up this error message

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 156, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 137, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\forms\preferencescontroller.py", line 53, in **init**
    self.updateViewPreview()
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\forms\preferencescontroller.py", line 228, in updateViewPreview
    self.updaterfromexpr.updatefact(fact, previewexpressions[self.model.prefersimptrad])
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\updater.py", line 297, in updatefact
    ] + (self.config.shouldusegoogletranslate and [
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\config.py", line 364, in getshouldusegoogletranslate
    self.__googletranslateworking = dictionaryonline.gCheck(self.dictlanguage)
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 50, in gCheck
    lookup(u"好", destlanguage)
  File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 100, in lookup
    return [[Word(Text(result[0]))]] + [[Word(Text(definition[0].capitalize() + ": " + ", ".join(definition[1:])))] for definition in result[1]]
TypeError: sequence item 0: expected string, list found

**Comment by batterseapower** [comment]
This Pinyin Toolkit problem was caused by a change that Google made to the Google Translate response format. Please install v0.6.4 from the "Shared Plugins" menu to fix the bug.

**Comment by Zinbiel** [comment]
I've got the exact same error report as Spaldos. I use pinyin toolkit pretty much everyday, then yesterday errors have come up.

edit: thanks a lot

edit2: when updating database, I get

File "C:\Users\Jason\Appdata\Roaming.anki\plugins\forms\builddbcontroller.py",
line 54, in run
File "C:\Users\Jason\Appdata\Roaming.anki\plugins\pinyin\db\builder.py", line 52, in build
AttributeError: 'module' object has no attribute 'getDBConnector'

**Comment by yinzi** [comment]
installed new version, worked like a charm. thanks so much.
