### ISSUE TITLE
Startup error when using Anki 0.9.9.8.6

### ISSUE THREAD

**Issue by lwb0706** [batterseapower/pinyin-toolkit#158]
After installing Anki 0.9.9.8.6, I get this error when starting it up:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "ankiqt\ui\main.pyc", line 2472, in loadPlugins
  File "C:\Documents and Settings\Loren\Application Data.anki\plugins\Pinyin Toolkit.py", line 29, in 
  File "C:\Documents and Settings\Loren\Application Data.anki\plugins\pinyin__init__.py", line 16, in 
  File "C:\Documents and Settings\Loren\Application Data.anki\plugins\pinyin\config.py", line 6, in 
  File "C:\Documents and Settings\Loren\Application Data.anki\plugins\pinyin\dictionaryonline.py", line 7, in 
  File "C:\Documents and Settings\Loren\Application Data.anki\plugins\pinyin\model.py", line 6, in 
ImportError: No module named sgmllib

**Comment by batterseapower** [comment]
Thing has been fixed for a long time. Use the shared plugins menu to install the latest version of the Pinyin Toolkit.

Thanks,
Max
