### ISSUE TITLE
ImportError: No module named exc (sqlalchemy)

### ISSUE THREAD

**Issue by ghost** [batterseapower/pinyin-toolkit#163]
I received this error message after I had reinstalled Anki (0.9.9.8.6) on my PC. I am running Ubuntu 9.04. I have both Python 2.5 and 2.6 installed and both have the sqlalchemy library.

"An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "/usr/share/anki/ankiqt/ui/main.py", line 2472, in loadPlugins
    **import**(nopy)
  File "/home/jfca/.anki/plugins/Pinyin Toolkit.py", line 29, in 
    import pinyin.anki.main as main
  File "/home/jfca/.anki/plugins/pinyin/anki/main.py", line 11, in 
    import pinyin.db.builder
  File "/home/jfca/.anki/plugins/pinyin/db/builder.py", line 3, in 
    import cjklib.build
  File "/home/jfca/.anki/plugins/pinyin/../pinyin/vendor/cjklib/cjklib/build/**init**.py", line 60, in 
    from sqlalchemy.exc import OperationalError
ImportError: No module named exc"

**Comment by batterseapower** [comment]
Your SQL Alchemy version is too old. Perhaps you can upgrade it like this:

sudo apt-get update
sudo apt-get -u install python-sqlalchemy
