### ISSUE TITLE
Clean install of Anki + pinyin toolkit on Ubuntu - error in a plugin

### ISSUE THREAD

**Issue by s85** [batterseapower/pinyin-toolkit#169]
An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
File "/usr/share/anki/ankiqt/ui/main.py", line 2117, in loadPlugins
**import**(nopy)
File "/home/s85/.anki/plugins/Pinyin Toolkit.py", line 29, in 
import pinyin.anki.main as main
File "/home/s85/.anki/plugins/pinyin/**init**.py", line 23, in 
import config
File "/home/s85/.anki/plugins/pinyin/config.py", line 6, in 
import dictionaryonline
File "/home/s85/.anki/plugins/pinyin/dictionaryonline.py", line 7, in 
from model import *
File "/home/s85/.anki/plugins/pinyin/model.py", line 6, in 
from BeautifulSoup import BeautifulSoup, Tag
ImportError: No module named BeautifulSoup

**Comment by s85** [comment]
Anki 0.9.9.7.8 
pinyin-toolkit - downloaded via shared plugin download in Anki

**Comment by batterseapower** [comment]
You need to install the BeautifulSoup Python library. Something like:

  sudo apt-get install python-beautifulsoup

**Comment by s85** [comment]
thank you for the advice, everything is ok now
