### ISSUE TITLE
error when trying to install pinyin toolkit plugin to anki

### ISSUE THREAD

**Issue by shalun** [batterseapower/pinyin-toolkit#173]
On a clean install of Anki I am trying to install the pinyin toolkit (which I had previously and installed with no problem).  When the plugin has been downloaded and I am prompted to restart anki I do.  I then get this error:

插件错误。请联系插件作者。
请勿向Anki提交bug。

Traceback (most recent call last):
  File "logging__init__.pyc", line 760, in emit
  File "logging__init__.pyc", line 644, in format
  File "logging__init__.pyc", line 444, in format
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 52: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\ɯ�\AppData\Roaming.anki\plugins\pinyin\forms\builddbcontroller.py", line 72, in 
    view.connect(self.thread, SIGNAL("buildfailure(PyQt_PyObject)"), lambda e: buildFailure(e))
  File "C:\Users\ɯ�\AppData\Roaming.anki\plugins\pinyin\forms\builddbcontroller.py", line 68, in buildFailure
    notifier.exception("There was an error while building the Pinyin Toolkit database!", e)
  File "C:\Users\ɯ�\AppData\Roaming.anki\plugins\pinyin\anki\notifier.py", line 30, in exception
    ankiqt.ui.utils.showWarning(text + u"\r\nThe exception was:\r\n" + "".join(traceback.format_exception(*exception_info)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 52: ordinal not in range(128)

Any ideas on how to fix this?

**Comment by batterseapower** [comment]
Turns out this was fixed by moving to an account with a non-Chinese username. I guess part of our path formatting assumes paths are ANSI? Must look into this.
