### ISSUE TITLE
not working at all. eek!

### ISSUE THREAD

**Issue by yinzi** [batterseapower/pinyin-toolkit#177]
i get this message whenever I try. 
nothing works - pinyin, meaning, etc; all fields left blank.

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "C:\Users\Private\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 180, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.mw.deck is not None and self.triggered())
  File "C:\Users\Private\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 194, in triggered
    getattr(self.updaters[field], self.**class**.updatehow)(factproxy, factproxy[field])
  File "C:\Users\Private\AppData\Roaming.anki\plugins\pinyin\updater.py", line 297, in updatefact
    ] + (self.config.shouldusegoogletranslate and [
  File "C:\Users\Private\AppData\Roaming.anki\plugins\pinyin\config.py", line 364, in getshouldusegoogletranslate
    self.__googletranslateworking = dictionaryonline.gCheck(self.dictlanguage)
  File "C:\Users\Private\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 50, in gCheck
    lookup(u"好", destlanguage)
  File "C:\Users\Private\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 100, in lookup
    return [[Word(Text(result[0]))]] + [[Word(Text(definition[0].capitalize() + ": " + ", ".join(definition[1:])))] for definition in result[1]]
TypeError: sequence item 0: expected string, list found

anyone have a similar problem/solution, or did i do anything stupid?
(i haven't touched it since it was working, about 3 weeks ago, so settings shouldn't have changed..)

thanks!

**Comment by batterseapower** [comment]
This Pinyin Toolkit problem was caused by a change that Google made to the Google Translate response format. Please install v0.6.4 from the "Shared Plugins" menu to fix the bug.
