### ISSUE TITLE
Toolkit, all of sudden, ceased working for me, no idea why, error message inside

### ISSUE THREAD

**Issue by spaldos** [batterseapower/pinyin-toolkit#178]
I get this error message, no idea why it started happening! I had been using the toolkit happily (cheers btw) for months. Tried reinstalling, no change. Anyway, here's what it said..

Traceback (most recent call last):
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 156, in
self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 137, in triggered
controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\forms\preferencescontroller.py", line 53, in **init**
self.updateViewPreview()
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\forms\preferencescontroller.py", line 228, in updateViewPreview
self.updaterfromexpr.updatefact(fact, previewexpressions[self.model.prefersimptrad])
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\updater.py", line 297, in updatefact
] + (self.config.shouldusegoogletranslate and [
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\config.py", line 364, in getshouldusegoogletranslate
self.__googletranslateworking = dictionaryonline.gCheck(self.dictlanguage)
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 50, in gCheck
lookup(u"好", destlanguage)
File "C:\Users\Randy\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 100, in lookup
return [[Word(Text(result[0]))]] + [[Word(Text(definition[0].capitalize() + ": " + ", ".join(definition[1:])))] for definition in result[1]]
TypeError: sequence item 0: expected string, list found

**Comment by batterseapower** [comment]
This Pinyin Toolkit problem was caused by a change that Google made to the Google Translate response format. Please install v0.6.4 from the "Shared Plugins" menu to fix the bug.
