### ISSUE TITLE
Google format changed again?

### ISSUE THREAD

**Issue by Gingerjim** [batterseapower/pinyin-toolkit#181]
Hi Max,

Anki Toolkit has just stopped working for me with single characters and most sentences.  I managed to generate the following error by digging around in Settings/Pinyin Toolkit Sentences.   I think maybe Google has just changed something because before this it has been a great tool.  Thanks for your hard work.

Cheers, Jim

---

**\* Error Log 

---

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 156, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\anki\hooks.py", line 137, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\forms\preferencescontroller.py", line 53, in **init**
    self.updateViewPreview()
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\forms\preferencescontroller.py", line 228, in updateViewPreview
    self.updaterfromexpr.updatefact(fact, previewexpressions[self.model.prefersimptrad])
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\updater.py", line 297, in updatefact
    ] + (self.config.shouldusegoogletranslate and [
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\config.py", line 364, in getshouldusegoogletranslate
    self.__googletranslateworking = dictionaryonline.gCheck(self.dictlanguage)
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 50, in gCheck
    lookup(u"好", destlanguage)
  File "C:\Users\lenovoviper\AppData\Roaming.anki\plugins\pinyin\dictionaryonline.py", line 100, in lookup
    return [[Word(Text(result[0]))]] + [[Word(Text(definition[0].capitalize() + ": " + ", ".join(definition[1:])))] for definition in result[1]]
TypeError: sequence item 0: expected string, list found

**Comment by batterseapower** [comment]
Hi Jim,

Have you upgraded to v0.6.5? There was a change in the Google Translate format recently, which I have handled in that version.

Max

**Comment by Gingerjim** [comment]
Sorry Max, just found the other comments from people with the same problem as me.  Was looking for a way to delete my issue!  I'll go and upgrade now.
