### ISSUE TITLE
"fill missing card data" not working

### ISSUE THREAD

**Issue by xiaoju** [batterseapower/pinyin-toolkit#182]
Hi, 

When doing Tools -> Piyin Toolkit -> fill missing card data, 
the cards are not fill in, I get following bug report.
The missing data I want to fill in is the pinyin field, based on the hanzi field.
(config: Windows XP, Anki Rev. 0.9.9.8.6, Piyin Toolkit Rev. ???)
I've run "tools -> advanced -> check database", but not better.)

Same problem when selecting 
settings -> Piyin Toolkit Preferences

---

automatic bug report when trying fill missing data

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\anki\hooks.py", line 180, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.mw.deck is not None and self.triggered())
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\anki\hooks.py", line 194, in triggered
    getattr(self.updaters[field], self.**class**.updatehow)(factproxy, factproxy[field])
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\updater.py", line 297, in updatefact
    ] + (self.config.shouldusegoogletranslate and [
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\config.py", line 364, in getshouldusegoogletranslate
    self.__googletranslateworking = dictionaryonline.gCheck(self.dictlanguage)
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\dictionaryonline.py", line 50, in gCheck
    lookup(u"好", destlanguage)
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\dictionaryonline.py", line 100, in lookup
    return [[Word(Text(result[0]))]] + [[Word(Text(definition[0].capitalize() + ": " + ", ".join(definition[1:])))] for definition in result[1]]
TypeError: sequence item 0: expected string, list found

---

automatic bug report when trying toolkit preferences:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\anki\hooks.py", line 156, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\anki\hooks.py", line 137, in triggered
    controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 53, in **init**
    self.updateViewPreview()
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 228, in updateViewPreview
    self.updaterfromexpr.updatefact(fact, previewexpressions[self.model.prefersimptrad])
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\updater.py", line 297, in updatefact
    ] + (self.config.shouldusegoogletranslate and [
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\config.py", line 364, in getshouldusegoogletranslate
    self.__googletranslateworking = dictionaryonline.gCheck(self.dictlanguage)
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\dictionaryonline.py", line 50, in gCheck
    lookup(u"好", destlanguage)
  File "C:\Documents and Settings\TheFirstUser\Application Data.anki\plugins\pinyin\dictionaryonline.py", line 100, in lookup
    return [[Word(Text(result[0]))]] + [[Word(Text(definition[0].capitalize() + ": " + ", ".join(definition[1:])))] for definition in result[1]]
TypeError: sequence item 0: expected string, list found

---

**Comment by batterseapower** [comment]
Hi XiaoJu,

Please upgrade to v0.6.5, it fixes this problem, which was caused by a change at Google.

Cheers,
Max

**Comment by xiaoju** [comment]
now working! Thanks!
