### ISSUE TITLE
UnicodeDecodeError when tabbing out of Expression field

### ISSUE THREAD

**Issue by dahu** [batterseapower/pinyin-toolkit#184]
I get this error when I tab out of the expression field containing chinese characters:

Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.6/logging/handlers.py", line 144, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib/python2.6/logging/**init**.py", line 648, in format
    return fmt.format(record)
  File "/usr/lib/python2.6/logging/**init**.py", line 448, in format
    s = s + record.exc_text
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 705: ordinal not in range(128)

I'm using Anki 1.0.1 and Pinyin Toolkit 6.0.5.

Several days ago when I created the deck and inserted 50 cards, the pinyin toolkit plugin worked beautifully. However, when I came back to enter more cards, I got this error.

**Comment by amasover** [comment]
I'm not sure if this is related, but the UnicodeDecodeError prevents me from even adding the Pinyin toolkit plugin to anki. Pinyin Toolkit never finishes building its database on first run; the window just hangs and a debug window pops up:

外掛發生錯誤. 請連絡外掛的作者.
請不要對 Anki 做錯誤回報.

Traceback (most recent call last):
  File "logging__init__.pyc", line 744, in emit
  File "logging__init__.pyc", line 630, in format
  File "logging__init__.pyc", line 430, in format
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa6 in position 52: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\��AppData\Roaming.anki\plugins\pinyin\forms\builddbcontroller.py", line 72, in 
    view.connect(self.thread, SIGNAL("buildfailure(PyQt_PyObject)"), lambda e: buildFailure(e))
  File "C:\Users\��AppData\Roaming.anki\plugins\pinyin\forms\builddbcontroller.py", line 68, in buildFailure
    notifier.exception("There was an error while building the Pinyin Toolkit database!", e)
  File "C:\Users\��AppData\Roaming.anki\plugins\pinyin\anki\notifier.py", line 30, in exception
    ankiqt.ui.utils.showWarning(text + u"\r\nThe exception was:\r\n" + "".join(traceback.format_exception(*exception_info)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa6 in position 52: ordinal not in range(128)
