### ISSUE TITLE
plugin error, doesn't lookup definitions

### ISSUE THREAD

**Issue by svoboda** [batterseapower/pinyin-toolkit#185]
I recently had to reinstall anki and all the componets. After downloading the pinyin toolkit, I got an error message. When I run anki, if I enter a hanzi character, it will provide the pinyin, but the definition is blank. Is this problem related to the error message?

Here is the error message:
An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):

File "logging__init__.pyc", line 744, in emit

File "logging__init__.pyc", line 630, in format

File "logging__init__.pyc", line 430, in format

UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 52: ordinal not in range(128)

Traceback (most recent call last):

File "C:\Users\ʷ־��Andrew Svoboda\AppData\Roaming.anki\plugins\pinyin\forms\builddbcontroller.py", line 72, in

view.connect(self.thread, SIGNAL("buildfailure(PyQt_PyObject)"), lambda e: buildFailure(e))

File "C:\Users\ʷ־��Andrew Svoboda\AppData\Roaming.anki\plugins\pinyin\forms\builddbcontroller.py", line 68, in buildFailure

notifier.exception("There was an error while building the Pinyin Toolkit database!", e)

File "C:\Users\ʷ־��Andrew Svoboda\AppData\Roaming.anki\plugins\pinyin\anki\notifier.py", line 30, in exception

ankiqt.ui.utils.showWarning(text + u"\r\nThe exception was:\r\n" + "".join(traceback.format_exception(*exception_info)))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 52: ordinal not in range(128)

**Comment by svoboda** [comment]
Originally my user name contained hanzi, but after reading another post, I removed the hanzi, however this did not correct the problem.

**Comment by svoboda** [comment]
the plugin I'm having the problem with is the 0.6.5pinyin toolkit

**Comment by batterseapower** [comment]
Duplicate of #186
