### ISSUE TITLE
Opening the demo decks

### ISSUE THREAD

**Issue by Ricky1194** [batterseapower/pinyin-toolkit#187]
Here is the error I get everytime that I try to install the demo decks:

Traceback (most recent call last):
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/anki.deck", line 3698, in Deck
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/anki.deck", line 4369, in _upgradeDeck
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/anki.deck", line 3846, in _addIndices
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/anki.db", line 114, in statement
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/anki.db", line 90, in execute
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.orm.session", line 701, in execute
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 1194, in execute
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 1274, in _execute_clauseelement
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 1305, in __execute_context
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 1404, in _cursor_execute
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 1397, in _cursor_execute
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.default", line 299, in do_execute
IntegrityError: (IntegrityError) indexed columns are not unique u'\ncreate unique index if not exists ix_tags_tag on tags (tag)' ()

**Comment by batterseapower** [comment]
Do the updated demo decks at http://batterseapower.github.com/pinyin-toolkit/files/pytk-demo-deck-0.9.9.8.1-v2.zip work for you?
