### ISSUE TITLE
Error message, toolkit 0.6.6 does not load

### ISSUE THREAD

**Issue by on-land** [batterseapower/pinyin-toolkit#198]
Hi,

After reinstalling the Pinyin Toolkit I get an error at Anki startup (below), and the Toolkit does not seem to function. I am on Mac OSX 10.5.8, Anki 1.2.8, Pinyin Toolkit 0.6.6. I used to use the Toolkit with Anki up till a year ago, then had a break. Starting up again, the new version of Anki reviews my old decks fine, but told me to get new version of Toolkit to add new cards. Is there something simple that I missed? I appreciate any help, I can't imagine using Anki without this plugin.

-Alexei

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "ankiqt/ui/main.pyc", line 2679, in loadPlugins
  File "/Users/Alexei/Library/Application Support/Anki/plugins/Pinyin Toolkit.py", line 29, in 
  File "/Users/Alexei/Library/Application Support/Anki/plugins/pinyin/anki/main.py", line 17, in 
  File "/Users/Alexei/Library/Application Support/Anki/plugins/pinyin/anki/hooks.py", line 9, in 
  File "/Users/Alexei/Library/Application Support/Anki/plugins/pinyin/factproxy.py", line 3, in 
ImportError: No module named logger

**Comment by on-land** [comment]
Fixed
