### ISSUE TITLE
Broken plugin at startup

### ISSUE THREAD

**Issue by mornir** [batterseapower/pinyin-toolkit#205]
I have this error when I open Anki and the pinyin toolkit doesn't seem to work.

"
2012-02-06 09:14:32,216 - ERROR - A thunked action raised an exception! Letting it go through and hoping for the best...
Traceback (most recent call last):
  File "C:\Users\Jérôme\AppData\Roaming.anki\plugins\pinyin\utils.py", line 185, in **call**
    self.**result = self.__function()
  File "C:\Users\Jérôme\AppData\Roaming.anki\plugins\pinyin\db__init**.py", line 10, in <lambda>
    database = pinyin.utils.Thunk(lambda: cjklib.dbconnector.getDBConnector({ "url" : sqlalchemy.engine.url.URL("sqlite", database=dbpath) }))
  File "C:\Users\Jérôme\AppData\Roaming.anki\plugins\pinyin..\pinyin\vendor\cjklib\cjklib\dbconnector.py", line 167, in getDBConnector
    _dbconnectInst = DatabaseConnector(databaseSettings)
  File "C:\Users\Jérôme\AppData\Roaming.anki\plugins\pinyin..\pinyin\vendor\cjklib\cjklib\dbconnector.py", line 276, in __init__
    self.connection = self.engine.connect()
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 1814, in connect
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 835, in **init**
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.base", line 1877, in raw_connection
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.pool", line 143, in unique_connection
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.pool", line 370, in **init**
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.pool", line 214, in get
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.pool", line 600, in do_get
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.pool", line 148, in create_connection
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.pool", line 254, in **init**
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.pool", line 320, in __connect
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.strategies", line 76, in connect
  File "C:\cygwin\home\dae\Home\anki\win\build\pyi.win32\anki\outPYZ1.pyz/sqlalchemy.engine.default", line 249, in connect
OperationalError: (OperationalError) unable to open database file None None
"

Could you help me fix it?
Thanks

**Comment by mornir** [comment]
screenshot: http://postimage.org/image/3tszq1nqz/

**Comment by mornir** [comment]
I think I figured out why it didn't work. There's a problem in the file path. The plugin can't access its database because of the user name folder "Jérôme".
