### ISSUE TITLE
no more automatically generated readings and meanings

### ISSUE THREAD

**Issue by unsermanninchina** [batterseapower/pinyin-toolkit#212]
since some while still using kubuntu 11.10 kde 4.8.1 or 4.8.2 automatically generated sounds, readings and meanings doesn't work anymore, regardless using German or English. Google doesn't translate, too. It just stays empty.

BStill working is this: you add manually pinyin with numbers it's still changing it into coloured pinyin tone version. Manually adding the pinyin into the sound field it's finding the soundfiles as well.

But, that's half of the fun :-(

**Comment by vershinin** [comment]
I have this issue too in Debian Sid.
Anki version is 1.2.9, toolkit version is 0.6.6

**Comment by arkhi** [comment]
So do I on Ubuntu 12.04, with Anki 1.2.9 and Pinyin Toolkit 0.6.6.

Here is what Anki tells me; I am of course connected as "fabien":

> An error occurred in a plugin. Please contact the plugin author.
> Please do not file a bug report with Anki.
> 
> Traceback (most recent call last):
>   File "/usr/share/anki/ankiqt/ui/main.py", line 2680, in loadPlugins
>     **import**(nopy)
>   File "/home/fabien/.anki/plugins/Pinyin Toolkit.py", line 29, in 
>     import pinyin.anki.main as main
>   File "/home/fabien/.anki/plugins/pinyin/anki/main.py", line 11, in 
>     import pinyin.db.builder
>   File "/home/fabien/.anki/plugins/pinyin/db/builder.py", line 3, in 
>     import cjklib.build
>   File "/home/fabien/.anki/plugins/pinyin/../pinyin/vendor/cjklib/cjklib/build/**init**.py", line 62, in 
>     from sqlalchemy.exceptions import OperationalError
> ImportError: No module named exceptions

Anybody could help with that? :)

**Comment by unsermanninchina** [comment]
The cjklib is outdated (And there is no new one). There are wrong python requests. 
Check in ~/.anki/plugins/pinyin/vendor/cjklib/cjklib/buuild/builder.py
for "sqlalchemy.exceptions" and change it into "sqlalchemy.exc"
That should do it for pinyin tootlkit.

Out of topic, but maybe people use cjklib for other software too:
I have the same problem with other software using cjklib (here Eclectus)
In the case of Eclectus the wrong files are here:
/usr/lib/python2.7/dist-packages/cjklib/build/cli.py
/usr/lib/python2.7/dist-packages/cjklib/build/builder.py
/usr/lib/python2.7/dist-packages/cjklib/build/init.py
/usr/local/lib/python2.7/dist-packages/eclectusqt/update.py

**Comment by unsermanninchina** [comment]
This actually doesn't solve the problem mentioned in this issue. But pinyintoolkit is starting with this changes.

**Comment by vershinin** [comment]
Solution was to install new anki version (1.2.11)

**Comment by unsermanninchina** [comment]
Same here, installing 1.2.11 and pinyin-toolkit runs again like before.
