### ISSUE TITLE
startup error: No module named exceptions

### ISSUE THREAD

**Issue by xrchz** [batterseapower/pinyin-toolkit#213]
I just installed the plugin on Anki 1.2.11, restarted Anki, and was greeted with this error:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ankiqt/ui/main.py", line 2679, in loadPlugins
    **import**(nopy)
  File "/home/ramana/.anki/plugins/Pinyin Toolkit.py", line 29, in 
    import pinyin.anki.main as main
  File "/home/ramana/.anki/plugins/pinyin/anki/main.py", line 11, in 
    import pinyin.db.builder
  File "/home/ramana/.anki/plugins/pinyin/db/builder.py", line 3, in 
    import cjklib.build
  File "/home/ramana/.anki/plugins/pinyin/../pinyin/vendor/cjklib/cjklib/build/**init**.py", line 62, in 
    from sqlalchemy.exceptions import OperationalError
ImportError: No module named exceptions

What's wrong?

**Comment by ospalh** [comment]
It's abandoned. That's what's wrong.
You can try the [patch](https://gist.github.com/2630334) or the anki1 branch of [my fork](https://github.com/ospalh/pinyin-toolkit/tree/anki1). (Which is basically just the same patch).

Or, when you want to use Anki 2, you can help by starting to work on the new [Chinese addon](https://github.com/ospalh/chinese-support-addon). Or write your own ^_^ .
