### ISSUE TITLE
Auto-Download of Audio Fails

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#35]
Traceback (most recent call last):
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 118, in 
    self.view.connect(self.view.controls.installMandarinSoundsButton, SIGNAL("clicked()"), lambda: self.installMandarinSounds())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\forms\preferencescontroller.py", line 147, in installMandarinSounds
    pinyin.media.downloadAndInstallMandarinSounds(self.notifier, self.mediamanager, self.model)
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\media.py", line 22, in downloadAndInstallMandarinSounds
    the_media.installpack(mediamanager.mediadir())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\media.py", line 77, in installpack
    thezip = zipfile.ZipFile(self.zippath)
  File "zipfile.pyc", line 346, in **init**
  File "zipfile.pyc", line 366, in _GetContents
  File "zipfile.pyc", line 378, in _RealGetContents
zipfile.BadZipfile: File is not a zip file

**Comment by batterseapower** [comment]
This is because the Mandarin Sounds website is down. Your suggestion:

How about when you click on downlload it gives you the prompt, but also a prompt field for the URL to download from. It can default to mandarin sounds every time (wherever we eventually put it) but we can make it work for any possible zip. that would mean we could invite people to type in these sort of urls (eg chinesepod) in the readme. That way we haven't done the downloading or made it automatic, we've just told people what the software does and let them use it as they like.

**Comment by Nick3C** [comment]
we should cover that eventuality... the web is the web after all. And some foold may try downloading when not connected :)

**Comment by batterseapower** [comment]
Improve handling of exceptions when downloading media pack. Closed by 5b16811dc72e830cc2a97129750ba2a182935324
