### ISSUE TITLE
Missing fields cause exception

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#39]
deck without measure word field:

Traceback (most recent call last):
 File "ankiqt\ui\facteditor.pyc", line 398, in
 File "ankiqt\ui\facteditor.pyc", line 490, in onFocusLost
 File "anki\facts.pyc", line 125, in focusLost
 File "anki\hooks.pyc", line 26, in runHook
 File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 45, in onFocusLost
   pinyin.utils.suppressexceptions(lambda: self.updater.updatefact(factproxy, field.value))
 File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\utils.py", line 33, in suppressexceptions
   action()
 File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 45, in
   pinyin.utils.suppressexceptions(lambda: self.updater.updatefact(factproxy, field.value))
 File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 178, in updatefact
   if not(key in fact) or not(enabled) or fact[key].strip() != u"":
 File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\utils.py", line 20, in **getitem**
   return self.fact[self.fieldnames[key]]
 File "anki\facts.pyc", line 84, in **getitem**
KeyError: None

**Comment by Nick3C** [comment]
I have just looked at this, this is the new fact proxy that is causing this. I tried to fiddle with it to add some conditions... all I managed to do was get different key-zero errors instead :)

It is a fairly serious bug and we certainly can't release without fixing it.

**Comment by batterseapower** [comment]
This is fixed in my fork.
