### ISSUE TITLE
Tone Sandhi Generation Error (Also breaks Mass-Fill)

### ISSUE THREAD

**Issue by Nick3C** [batterseapower/pinyin-toolkit#80]
Traceback (most recent call last):
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 123, in 
    self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 175, in triggered
    self.updater.updatefact(factproxy, factproxy["expression"])
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 149, in updatefact
    dictreading = transformations.tonesandhi(self.config.dictionary.reading(expression))
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\transformations.py", line 63, in tonesandhi
    assert tonecontourqueue.pop() == "~"
AssertionError

**Comment by Nick3C** [comment]
I think I have found the cause of this.... try adding:
 妮妮你你你你你 (yes, it's nonsense, but I was testing tone sandhi rules)

 File "ankiqt\ui\facteditor.pyc", line 397, in 
  File "ankiqt\ui\facteditor.pyc", line 489, in onFocusLost
  File "anki\facts.pyc", line 125, in focusLost
  File "anki\hooks.pyc", line 26, in runHook
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 38, in onFocusLost
    pinyin.utils.suppressexceptions(lambda: self.updater.updatefact(factproxy, field.value))
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\utils.py", line 34, in suppressexceptions
    action()
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\anki\hooks.py", line 38, in 
    pinyin.utils.suppressexceptions(lambda: self.updater.updatefact(factproxy, field.value))
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\updater.py", line 149, in updatefact
    dictreading = transformations.tonesandhi(self.config.dictionary.reading(expression))
  File "C:\Documents and Settings\Nick\Application Data.anki\plugins\pinyin\transformations.py", line 63, in tonesandhi
    assert tonecontourqueue.pop() == "~"
IndexError: pop from empty list

Seems to be a problem with 3 or more third tones together (which clearly exist in some phrases in my deck)

**Comment by Nick3C** [comment]
see further commentary at Anki Forum thread here: http://groups.google.com/group/ankisrs/browse_thread/thread/b9696e0f7cc4c209#

**Comment by Nick3C** [comment]
Realworld example:
泳有小姐 of the phrase 如果游泳有小姐陪。那如果裸体我就去就餐。

also:
酒水饮料

**Comment by batterseapower** [comment]
Proper fix for the tone sandhi issue, Closed by d368314321fb18a26b3cff4cdd12941d2109ad09
