### ISSUE TITLE
anki (0.9.9.8.4-1) reports plugin error on loading toolkit (0.05)

### ISSUE THREAD

**Issue by poikiloid** [batterseapower/pinyin-toolkit#99]
this is an otherwise working installation of anki running on ubuntu jaunty 9.04. i do have the audio media in the media folder, but this error appeared before i added that. the error mssg follows:

An error occurred in a plugin. Please contact the plugin author.
Please do not file a bug report with Anki.

Traceback (most recent call last):
  File "/usr/share/anki/ankiqt/ui/main.py", line 2384, in loadPlugins
    **import**(nopy)
  File "/home/erik/.anki/plugins/Pinyin Toolkit.py", line 43, in 
    import pinyin.anki.main as main
  File "/home/erik/.anki/plugins/pinyin/anki/**init**.py", line 2, in 
    import main
  File "/home/erik/.anki/plugins/pinyin/anki/main.py", line 15, in 
    import statsandgraphs
  File "/home/erik/.anki/plugins/pinyin/anki/statsandgraphs.py", line 18, in 
    from ankiqt.ui.graphs import AdjustableFigure, GraphWindow
  File "/usr/share/anki/ankiqt/ui/graphs.py", line 12, in 
    from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
ImportError: No module named matplotlib.backends.backend_qt4agg

**Comment by batterseapower** [comment]
You need to install the python-matplotlib package. I'm keeping this ticket open as another person had the same problem, so I think we need some notification to tell people to do this.

**Comment by batterseapower** [comment]
Lazy-load ankiqt.ui.graphs and warn if import fails. Closed by f5b46f8d264072acc6462f2734211c0468599244
